### ISSUE TITLE
Trash files not showing up in client

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/storage-server#196]
Lots of files in trash:
https://www.googleapis.com/storage/v1/b/risemedialibrary-4522440d-9e3f-4494-b32d-1bf4bbe14732/o

No files listed:
https://storage-dot-rvaserver2.appspot.com/_ah/api/storage/v0.01/files?companyId=4522440d-9e3f-4494-b32d-1bf4bbe14732&folder=--TRASH--%2F

@fjvallarino please have a look.
@AlexKolenoff FYI

**Comment by btfrise** [comment]
@fjvallarino Have you had a chance to look at this yet?

**Comment by fjvallarino** [comment]
@btfrise Yes, the bucket upgrade process did not finish correctly for that companyId (it seems it took too long because of the number of files). I have an improved version that I will run as soon as it's peer reviewed.

**Comment by AlexKolenoff** [comment]
@fjvallarino Do you have a rough ETA?  This came to light because a client reported all of his files as missing so it leaves them in limbo right now and I would like to update them.

**Comment by fjvallarino** [comment]
@AlexKolenoff I'm not sure, because after it's approved, I have to run the process on prod for that bucket and see if it ran correctly. If it did not run, I have to look for alternatives. I can't test that it finish from my local environment, unfortunately.

**Comment by fjvallarino** [comment]
@AlexKolenoff @btfrise User should have access to their files now.

A process has been ran on all the existing buckets which changes Google Cloud Storage structure so Trash operations are faster (it also uses information from Datastore). It failed for this particular bucket, most likely because of the really high number of files, and that's why they were not able to access them.

@tejohnso FYI

**Comment by fjvallarino** [comment]
@AlexKolenoff @btfrise Can we close this issue? Thanks!

**Comment by AlexKolenoff** [comment]
@fjvallarino  I believe this can be closed; there were no further problems.  I am curious if this would fail again or was it just an anomaly?

**Comment by fjvallarino** [comment]
@AlexKolenoff This was an anomaly. This user was having issues because the process failed on their bucket, so unless it had failed for others it should not happen. Since it was ran more than a month ago and it's not going to be ran again, we should not have more issues (in case we do, the solution is running the process again for the failing bucket).

**Comment by AlexKolenoff** [comment]
Thanks @fjvallarino.  I am going to close this.  FYI @btfrise
